VERSION: 1.3
LANGUAGE: EN-US
#Remove all wrong machine from the database (when loaded first)
#This wrong means you config change (name of the blueprint or the type
#of the machine!
#You can change everything from an machine which is already in use, but
#don't change the name and the type!
REMOVE_MACHINE_WRONG: false
Database:
  #types: [SQLITE],[MYSQL]
  TYPE: SQLITE
  MYSQL:
    HOST: localhost
    USERNAME: root
    PASSWORD: root
    DB: arenax1
custom_items:
  my_custom_sword:
    type: diamond_sword
    display: "&bDiamond Sword"
    enchantments:
      sharpness: 10
      unbreaking: 3
    lore:
      - &bVery strong sword
      - &dBe careful!
  my_custom_fuel:
    type: coal
    display: "&dSUPER COAL"
    lore:
      - &dThis is a super coal!
      - &dUse in an custom machine!
machines:
#Obs: do not overflow the stack limit:
#ex: 128 diamonds =
#diamond: 64
#diamond: 64
#Obs2: 32 eggs:
#egg: 16
#egg: 16
#machine type: [fuel, ingredient] for now
  "custom_machine":
    type: fuel
    price: 4000
    design:
      #does not support custom items!
      wall: gold_block
      separator: obsidian
    build:
      diamond_block: 64
    produces:
      my_custom_sword: 4000
    fuels:
      my_custom_fuel:
        burn: 8000
        speed: 5
  "gold":
    type: fuel
    price: 4000
    design:
      wall: gold_block
      separator: obsidian
    build:
      diamond: 32
      obsidian: 8
      gold_block: 15
      iron_ingot: 8
    produces:
      gold_ore: 400
    fuels:
      coal:
        burn: 800
        speed: 1.5
      coal_block:
        burn: 7200
        speed: 2.5
      wood:
        burn: 150
        speed: 0.8
  "skeleton":
    type: fuel
    price: 4000
    design:
      wall: mossy_cobblestone
      separator: iron_block
    build:
      stone: 64
      iron_block: 20
    produces:
      bone: 50
      arrow: 50
    fuels:
      coal:
        burn: 800
        speed: 1.5
      coal_block:
        burn: 7200
        speed: 2.5
      wood:
        burn: 150
        speed: 0.8
  "blaze":
    type: fuel
    price: 4000
    design:
      wall: netherrack
      separator: gold_block
    build:
      stone: 64
      gold_block: 32
      netherrack: 64
    produces:
      blaze_rod: 600
    fuels:
      coal:
        burn: 800
        speed: 1.5
      coal_block:
        burn: 7200
        speed: 2.5
      wood:
        burn: 150
        speed: 0.8
  "macerator":
    type: ingredient
    price: 6000
    design:
      wall: cobblestone
      separator: iron_block
    build:
      stone: 64
      dirt: 64
      iron_ingot: 32
      diamond: 16
      redstone: 64
    produces:
      iron_ingot:
        quantity: 2
        with: iron_ore
        fuel: 200
      gold_ingot:
        quantity: 2
        with: gold_ore
        fuel: 200
      diamond:
        quantity: 4
        with: diamond_ore
        fuel: 800
      emerald:
        quantity: 3
        with: emerald_ore
        fuel: 800
      quartz:
        quantity: 8
        with: quartz_ore
        fuel: 300
    fuels:
      coal:
        burn: 800
        speed: 0.8
      coal_block:
        burn: 7200
        speed: 0.8
      wood:
        burn: 150
        speed: 0.6
  "solar":
    type: solar
    price: 10000
    design:
      wall: iron_block
      separator: lapis_block
    build:
      stone: 64
      iron_block: 32
      lapis_block: 9
    produces:
      coal: 200
      wood: 200
      iron_ore: 200
      gold_ore: 200
    fuels: #por tick - 1 segundo = 20 ticks
      night: 0.4
      day: 1.1
  "farmingstation":
    type: collector
    price: 10000
    design:
      wall: stone
      separator: iron_block
    build:
      stone: 64
      iron_block: 32
      lapis_block: 9
    collect:
      - pumpkin
      - melon
      - cactus
      - sugar
      - wheat
      - carrot
      - potato
    range:
      xz: 12
      y: 8
    fuels:
      wood:
        burn: 120
        efficiency: 0.8
      coal:
        burn: 1600
        efficiency: 1